name: C/C++ Make CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: depends
      run: | 
        apt-get install libtool pkg-config build-essential autoconf automake libzmq3-dev
        cd r5560_sdk
        make
        cd linux
        sudo cp libr5560.so.1.0.0 /usr/local/lib
        cd /usr/local/lib
        sudo ln -s libr5560.so.1.0.0 librprng.so
    - name: make
      run: |
        cd ~/library/C/lib
        make
